apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:

  resources:
    inputs:
      - name: docker-source
        type: git
    outputs:
      - name: builtImage
        type: image

  params:
    - name: pathToDockerFile
      type: string
      default: $(resources.inputs.docker-source.path)/demo-app/k8sdemo/Dockerfile
    - name: pathToContext
      type: string
      default: $(resources.inputs.docker-source.path)/demo-app/k8sdemo/Dockerfile
    - name: image-version
      type: string
    - name: environment
      type: string

  steps:

    - name: show-dockerfile
      image: busybox
      resources: {}
      script: cat $(params.pathToDockerFile)


    - name: show-docker-image-name
      image: busybox
      resources: {}
      script: echo $(resources.outputs.builtImage.url):$(params.image-version)


    - name: build-and-push
      args:
        - '--dockerfile=$(params.pathToDockerFile)'
        - '--destination=$(resources.outputs.builtImage.url):$(params.image-version)'
        - '--context=$(params.pathToContext)'
      command:
        - /kaniko/executor
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      image: 'gcr.io/kaniko-project/executor:v0.17.1'
      
      resources: {}
      securityContext:
        runAsUser: 0
---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-using-kubectl
spec:

  resources:
    inputs:
      - name: kubernetes-source
        type: git
      - name: image
        type: image

  params:
    - name: environment
      type: string
    - name: image-version
      type: string
    - name: path
      type: string
    - name: yamlPathToImage
      type: string

  steps:

    - name: environment
      image: busybox
      script: echo $(params.environment)


    - name: replace-image
      image: mikefarah/yq
      command: ["yq"]
      args:
        - "w"
        - "-i"
        - "$(params.path)/deployment.yaml"
        - "$(params.yamlPathToImage)"
        - "$(resources.inputs.image.url):$(params.image-version)"


    - name: show-finalyaml
      image: busybox
      script: cat $(params.path)/deployment.yaml
      
      
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
        - "-n"
        - "training-$(params.environment)"
