apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mytaskrun4
spec:
  taskRef:
    name: deploy-using-kubectl
  params:
    - name: namespace
      value: "default"
    - name: image-version
      value: "1234"
    - name: path
      value: /workspace/kubernetes-source/deployment
    - name: yamlPathToImage
      value: "spec.template.spec.containers[0].image"
  resources:
    inputs:
      - name: kubernetes-source
        resourceRef:
          name: training-tekton-git
      - name: image
        resourceRef:
          name: training-tekton-image
