apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-test-pvc-sc
spec:
  storageClassName: my-storage-class
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 50Mi