---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: lab.ibm.com/demo-operator-frontend:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/lab_v1beta1_mylabdemo_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the lab.ibm.com/v1beta1.MyLabDemo
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/lab_v1beta1_mylabdemo_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='lab.ibm.com', api_version='v1beta1', kind='MyLabDemo', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 60s for reconciliation to run
    k8s_facts:
      api_version: 'v1beta1'
      kind: 'MyLabDemo'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 6
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
