apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denyreviewsv2handler
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denyreviewsv2request
spec:
  compiledTemplate: checknothing
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyreviewsv2
spec:
  match: destination.labels["app"] == "ratings" && source.labels["app"]=="reviews" && source.labels["version"] == "v2"
  actions:
  - handler: denyreviewsv2handler
    instances: [ denyreviewsv2request ]
