apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdemo
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "90%"
  template:
    metadata:
      labels:
        app: k8sdemo
        version: current
    spec:
      containers:
      - name: k8sdemo
        image: niklaushirt/k8sdemo:1.0.1
        imagePullPolicy: Always 
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
          limits:
            cpu: "300m"
            memory: "500Mi"
        env:
          - name: PORT
            value : "3000"
          - name: APPLICATION_NAME
            value: k8sdemo
          - name: BACKEND_URL
            value: http://k8sdemo-backend-service.default.svc:3000/api
---
apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-service
spec:
  selector:
    app: k8sdemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32123
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: k8sdemo-service
  namespace: default
spec:
  host: k8sdemo-service-default.192.168.99.100.nip.io
  to:
    kind: Service
    name: k8sdemo-service
    weight: 100
  wildcardPolicy: None
