# A service account is provisioned for security purposes.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-1
  labels:
    app: tools-rbac
# For the service account to have access to the IBM Cloud Container
# Registry, it needs these additional secrets.
imagePullSecrets:
- name: bluemix-default-secret
- name: bluemix-default-secret-regional
- name: bluemix-default-secret-international
