apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl
  labels:
    app: kubectl
    rbac: service-account-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl
      rbac: service-account-1
  template:
    metadata:
      labels:
        app: kubectl
        rbac: service-account-1
    spec:
      serviceAccountName: service-account-1
      containers:
        - name: kubectl
          image: "niklaushirt/kubectl:1.14"
          imagePullPolicy: Always
          command: ["/bin/sleep", "3601"]