apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-service
spec:
  selector:
    app: k8sdemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32123
  type: NodePort

