apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-backend-service
spec:
  selector:
    app: k8sdemo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32124
  type: NodePort